### ISSUE TITLE
Collection names with numbers throws a player error

### ISSUE THREAD

**Issue by moladukes** [NoonPacific/White-Label-Web-Template#2]
Created a mixtape named "001" the player couldn't resolve the ID.

**Comment by coffee-cup** [comment]
Are there any console errors?

On Thu, Jun 23, 2016 at 6:29 PM Milo Delgado

<
mailto:Milo Delgado <notifications@github.com>
> wrote:

Created a mixtape named "001" the player couldn't resolve the ID.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/NoonPacific/White-Label-Web-Template/issues/2
, or
https://github.com/notifications/unsubscribe/AC519ejwsPdOxv8fg7DxUkrjxiajvdEoks5qOzMMgaJpZM4I9Y0E
.

https://github.com/NoonPacific/White-Label-Web-Template/issues/2

**Comment by moladukes** [comment]
Seems like it is the slug that is the issue not the name per say. Here is the console log:

<img width="530" alt="screen shot 2016-06-23 at 6 38 20 pm" src="https://cloud.githubusercontent.com/assets/1104139/16325302/bc5c4eba-3971-11e6-9de5-1bf2c4398750.png">

By renaming the url to "demo" seems to be fine.

**Comment by coffee-cup** [comment]
Thanks, I will look into it.

**Comment by AlexGivens** [comment]
The issue is with White Label – entirely numeric slugs are being queried as IDs. I'll add validation to ensure all slugs contain at least one letter, and will report back when the patch is live.

**Comment by juliansantaana** [comment]
Had this same issue first time i tried the app. Thanks!

**Comment by AlexGivens** [comment]
Deployed White Label version 0.9.8. URL slug fields now validate against entirely numerical values. Please be sure to update any existing label, collection, mixtape, or track URL slugs to include at least one non-numerical character.
